# Defines two organizations
#  - Orderer organization
#  - Org1  = Single peer organization
#    Uses the "Specs" to declare the peers instead of Template

##### Orderer for simple 
OrdererOrgs:
  - Name: Orderer
    Domain: simple.com
    #EnableNodeOUs: true
    Specs:
      - Hostname: orderer
      
#### Peers for simple
PeerOrgs:
  # Peer configuration for ACME
  - Name: Org1
    Domain: simple.com
    #EnableNodeOUs: true
    Specs:
      - Hostname: devpeer
        CommonName: devpeer
    Users:
      Count: 2



      